#------------------------------------------------------------------------------
#
#  Taida settings
#
#------------------------------------------------------------------------------

# Authentication method. Use 'http' for HTTP authentication done by the
# web server, 'taida' for authentication done by Taida or 'none' for no
# authentication, in which case the username 'public' is used.
#
AUTHENTICATION = none

# Print error message on the screen.
#
DEBUG_MODE = yes

# Location of the home directories.
#
HOME_DIRECTORIES = home

# Offer a read-only interface.
#
READ_ONLY = yes

# Support for user Javascripts. Right-click a .js file and select the option
# 'Execute Javascript' to execute the script.
#
USER_JAVASCRIPT = yes

# Support user websites. Files located in directory Website are accessible via
# https://<Taida hostname>/~<username>/. When a directory is requested, Taida will
# look for the file index.html.
#
USER_WEBSITES = yes
